package testmain

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
)

type GeneratedTestmain struct {
	TestFuncs []TestFuncs
	Content   []byte
}

type templateImport struct {
	Name string
	Path string
}

type templateData struct {
	Imports     []templateImport
	Tests       []TestFunc
	Benchmarks  []TestFunc
	FuzzTargets []TestFunc
	Examples    []TestFunc
	TestMain    *TestFunc
	ImportPath string
	ModulePath string
}

func GenerateTestmain(allFuncs []TestFuncs) ([]byte, error) {
	data := buildTemplateData(allFuncs)

	var buf bytes.Buffer
	if err := testmainTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing testmain template: %w", err)
	}

	return buf.Bytes(), nil
}

func buildTemplateData(allFuncs []TestFuncs) templateData {
	data := templateData{
		Imports: []templateImport{
			{Path: "os"},
			{Path: "reflect"},
			{Path: "testing"},
			{Path: "testing/internal/testdeps"},
		},
	}

	for i, tf := range allFuncs {
		pkg := tf.Package

		if len(pkg.InternalTestFiles) > 0 || tf.NeedTest {
			name := buildImportName("test", i)
			data.Imports = append(data.Imports, templateImport{Name: name, Path: pkg.ImportPath})
			filterAndPrefix(tf.Tests, "_test", name, &data.Tests)
			filterAndPrefix(tf.Benchmarks, "_test", name, &data.Benchmarks)
			filterAndPrefix(tf.FuzzTargets, "_test", name, &data.FuzzTargets)
			filterAndPrefix(tf.Examples, "_test", name, &data.Examples)
			if tf.TestMain != nil && tf.TestMain.Package == "_test" {
				data.TestMain = &TestFunc{Package: name, Name: tf.TestMain.Name}
			}
		}

		if len(pkg.ExternalTestFiles) > 0 || tf.NeedXtest {
			name := buildImportName("xtest", i)
			data.Imports = append(data.Imports, templateImport{Name: name, Path: pkg.ImportPath + "_test"})
			filterAndPrefix(tf.Tests, "_xtest", name, &data.Tests)
			filterAndPrefix(tf.Benchmarks, "_xtest", name, &data.Benchmarks)
			filterAndPrefix(tf.FuzzTargets, "_xtest", name, &data.FuzzTargets)
			filterAndPrefix(tf.Examples, "_xtest", name, &data.Examples)
			if tf.TestMain != nil && tf.TestMain.Package == "_xtest" {
				data.TestMain = &TestFunc{Package: name, Name: tf.TestMain.Name}
			}
		}
	}

	if len(allFuncs) > 0 {
		data.ImportPath = allFuncs[0].Package.ImportPath
		data.ModulePath = allFuncs[0].Package.ModulePath
	}

	if data.TestMain == nil && len(allFuncs) > 0 {
		for i := range allFuncs {
			if allFuncs[i].TestMain != nil {
				data.TestMain = allFuncs[i].TestMain
				break
			}
		}
	}

	return data
}

func buildImportName(kind string, index int) string {
	if index == 0 {
		return "_" + kind
	}
	return fmt.Sprintf("_%s%d", kind, index)
}

func filterAndPrefix(src []TestFunc, srcPkg, dstPkg string, dst *[]TestFunc) {
	for _, f := range src {
		if f.Package != srcPkg {
			continue
		}
		*dst = append(*dst, TestFunc{
			Package:   dstPkg,
			Name:      f.Name,
			Output:    f.Output,
			Unordered: f.Unordered,
		})
	}
}

var testmainTemplate = template.Must(template.New("testmain").Funcs(template.FuncMap{
	"joinImports": func(imports []templateImport) string {
		var b strings.Builder
		for _, imp := range imports {
			if imp.Name != "" {
				fmt.Fprintf(&b, "\t%s %q\n", imp.Name, imp.Path)
			} else {
				fmt.Fprintf(&b, "\t%q\n", imp.Path)
			}
		}
		return b.String()
	},
	"quote": func(s string) string {
		return fmt.Sprintf("%q", s)
	},
}).Parse(`// Code generated by gotestwasm. DO NOT EDIT.

package main

import (
{{ joinImports .Imports }}
)

var tests = []testing.InternalTest{
{{- range .Tests }}
	{"{{.Name}}", {{.Package}}.{{.Name}}},
{{- end }}
}

var benchmarks = []testing.InternalBenchmark{
{{- range .Benchmarks }}
	{"{{.Name}}", {{.Package}}.{{.Name}}},
{{- end }}
}

var fuzzTargets = []testing.InternalFuzzTarget{
{{- range .FuzzTargets }}
	{"{{.Name}}", {{.Package}}.{{.Name}}},
{{- end }}
}

var examples = []testing.InternalExample{
{{- range .Examples }}
	{"{{.Name}}", {{.Package}}.{{.Name}}, {{.Output | quote}}, {{.Unordered}}},
{{- end }}
}

func init() {
	testdeps.ModulePath = {{.ModulePath | quote}}
	testdeps.ImportPath = {{.ImportPath | quote}}
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)
{{- if .TestMain }}
	{{.TestMain.Package}}.{{.TestMain.Name}}(m)
	os.Exit(int(reflect.ValueOf(m).Elem().FieldByName("exitCode").Int()))
{{- else }}
	os.Exit(m.Run())
{{- end }}
}
`))
